using Accelerator.Pelckmans;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;

namespace Accelerator.Functions;
public sealed class PelckmansFunctions(IOfferStore store, PelckmansAuth auth, PelckmansPublisher publisher) {
 [Function("PelckmansCapabilities")] public async Task<IActionResult> Capabilities([HttpTrigger(AuthorizationLevel.Anonymous,"get",Route="pelckmans/capabilities")] HttpRequest req,CancellationToken ct)=>await Run(async()=>new OkObjectResult(await auth.Authenticate(req,ct)));
 [Function("PelckmansOffers")] public async Task<IActionResult> Offers([HttpTrigger(AuthorizationLevel.Anonymous,"get",Route="pelckmans/offers")] HttpRequest req,CancellationToken ct)=>await Run(async()=>{var a=await auth.Authenticate(req,ct);return new OkObjectResult((await store.List(ct)).Where(x=>a.Approver||Same(x.Offer.Owner,a.Username)));});
 [Function("PelckmansOffer")] public async Task<IActionResult> Offer([HttpTrigger(AuthorizationLevel.Anonymous,"get",Route="pelckmans/offers/{id}")] HttpRequest req,string id,CancellationToken ct)=>await Run(async()=>{var(d,_)=await Access(req,id,ct);return new OkObjectResult(d);});
 [Function("PelckmansCreate")] public async Task<IActionResult> Create([HttpTrigger(AuthorizationLevel.Anonymous,"post",Route="pelckmans/offers")] HttpRequest req,[Microsoft.Azure.Functions.Worker.Http.FromBody] CreateOffer body,CancellationToken ct)=>await Run(async()=>{var a=await auth.Authenticate(req,ct);if(!a.Editor)return new ForbidResult();var id=$"PEL_STUDIO_{Guid.NewGuid():N}".ToUpperInvariant();var o=new PelckmansOffer{Id=id,Name=(body.Name??"").Trim(),Type=body.Type,Owner=a.Username,Components=body.Components??[],Rule=body.Rule,History=[new(DateTimeOffset.UtcNow,a.Username,"Created")]};return new CreatedResult($"/api/pelckmans/offers/{id}",await store.Put(o,null,ct));});
 [Function("PelckmansUpdate")] public async Task<IActionResult> Update([HttpTrigger(AuthorizationLevel.Anonymous,"put",Route="pelckmans/offers/{id}")] HttpRequest req,string id,[Microsoft.Azure.Functions.Worker.Http.FromBody] UpdateOffer body,CancellationToken ct)=>await Run(async()=>{var(d,a)=await Access(req,id,ct);RequireETag(body.ETag);return new OkObjectResult(await store.Put(OfferWorkflow.Edit(d.Offer,a,body.Name,body.Components??[],body.Rule),body.ETag,ct));});
 [Function("PelckmansPreview")] public async Task<IActionResult> Preview([HttpTrigger(AuthorizationLevel.Anonymous,"post",Route="pelckmans/offers/{id}/preview")] HttpRequest req,string id,[Microsoft.Azure.Functions.Worker.Http.FromBody] VerifyRequest? body,CancellationToken ct)=>await Run(async()=>{var(d,_)=await Access(req,id,ct);OfferEngine.ValidateComplete(d.Offer);return new OkObjectResult(OfferEngine.Preview(d.Offer,body?.Basket));});
 [Function("PelckmansDiscovery")] public async Task<IActionResult> Discovery([HttpTrigger(AuthorizationLevel.Anonymous,"get",Route="pelckmans/catalog")] HttpRequest req,CancellationToken ct)=>await Run(async()=>{var a=await auth.Authenticate(req,ct);if(!a.Editor&&!a.Approver)return new ForbidResult();int.TryParse(req.Query["page"],out var page);int.TryParse(req.Query["pageSize"],out var size);return new OkObjectResult(await publisher.Discover(req.Query["search"],page,size,ct));});
 [Function("PelckmansDuplicate")] public async Task<IActionResult> Duplicate([HttpTrigger(AuthorizationLevel.Anonymous,"post",Route="pelckmans/offers/{id}/duplicate")] HttpRequest req,string id,CancellationToken ct)=>await Run(async()=>{var(d,a)=await Access(req,id,ct);if(!a.Editor)return new ForbidResult();var id2=$"PEL_STUDIO_{Guid.NewGuid():N}".ToUpperInvariant();var copy=d.Offer with{Id=id2,Name=$"Copy of {d.Offer.Name}",Owner=a.Username,Status=OfferStatus.Draft,Revision=1,ApprovedRevision=null,Approver=null,PublishedResources=new Dictionary<string,string>(),PublicationError=null,UpdatedAt=DateTimeOffset.UtcNow,History=[new(DateTimeOffset.UtcNow,a.Username,"Duplicated",d.Offer.Id)]};return new CreatedResult($"/api/pelckmans/offers/{id2}",await store.Put(copy,null,ct));});
 [Function("PelckmansVerify")] public async Task<IActionResult> Verify([HttpTrigger(AuthorizationLevel.Anonymous,"post",Route="pelckmans/offers/{id}/verify")] HttpRequest req,string id,[Microsoft.Azure.Functions.Worker.Http.FromBody] VerifyRequest? body,CancellationToken ct)=>await Run(async()=>{var(d,a)=await Access(req,id,ct);if(!a.Approver)return new ForbidResult();return new OkObjectResult(await publisher.Verify(d.Offer,body?.Basket,ct));});
 [Function("PelckmansAction")] public async Task<IActionResult> Action([HttpTrigger(AuthorizationLevel.Anonymous,"post",Route="pelckmans/offers/{id}/actions/{action}")] HttpRequest req,string id,string action,[Microsoft.Azure.Functions.Worker.Http.FromBody] OfferAction? body,CancellationToken ct)=>await Run(async()=>{var(d,a)=await Access(req,id,ct);RequireETag(body?.ETag);if(action.Equals("publish",StringComparison.OrdinalIgnoreCase))return new OkObjectResult(await Publish(d,a,body!.ETag!,ct));var next=action.ToLowerInvariant() switch{"submit"=>OfferWorkflow.Submit(d.Offer,a),"approve"=>OfferWorkflow.Approve(d.Offer,a),"reject"=>OfferWorkflow.Reject(d.Offer,a,body?.Comment??""),_=>throw new ArgumentException("Unknown action")};return new OkObjectResult(await store.Put(next,body!.ETag,ct));});
 async Task<StoreDocument> Publish(StoreDocument d,WorkspaceActor a,string etag,CancellationToken ct){OfferWorkflow.CanPublish(d.Offer,a);var claimed=d.Offer with{Status=OfferStatus.Publishing,UpdatedAt=DateTimeOffset.UtcNow,History=d.Offer.History.Append(new(DateTimeOffset.UtcNow,a.Username,"Publication claimed",Revision:d.Offer.Revision)).ToList()};var claim=await store.Put(claimed,etag,ct);try{var refs=await publisher.Publish(d.Offer,ct);return await store.Put(claimed with{Status=OfferStatus.Published,PublishedResources=refs,PublicationError=null,UpdatedAt=DateTimeOffset.UtcNow,History=claimed.History.Append(new(DateTimeOffset.UtcNow,a.Username,"Published",Revision:d.Offer.Revision)).ToList()},claim.ETag,ct);}catch(Exception e){return await store.Put(claimed with{Status=OfferStatus.PublishFailed,PublicationError=e.Message,UpdatedAt=DateTimeOffset.UtcNow,History=claimed.History.Append(new(DateTimeOffset.UtcNow,a.Username,"Publication failed",e.Message,d.Offer.Revision)).ToList()},claim.ETag,ct);}}
 async Task<(StoreDocument,WorkspaceActor)> Access(HttpRequest req,string id,CancellationToken ct){var a=await auth.Authenticate(req,ct);var d=await store.Get(id,ct)??throw new KeyNotFoundException();if(!a.Approver&&!Same(d.Offer.Owner,a.Username))throw new UnauthorizedAccessException("This offer is not available to the signed-in user.");return(d,a);}
 static bool Same(string x,string y)=>string.Equals(x,y,StringComparison.OrdinalIgnoreCase);static void RequireETag(string? x){if(string.IsNullOrWhiteSpace(x))throw new ArgumentException("The current ETag is required. Reload the offer and try again.");}
 static async Task<IActionResult> Run(Func<Task<IActionResult>> action){try{return await action();}catch(Exception e){return Error(e);}}
 static IActionResult Error(Exception e)=>e switch{Azure.RequestFailedException x when x.Status is 409 or 412=>new ObjectResult(new{error="This offer changed since it was loaded. Reload it before trying again."}){StatusCode=412},UnauthorizedAccessException=>new ObjectResult(new{error=e.Message}){StatusCode=403},ArgumentException=>new BadRequestObjectResult(new{error=e.Message}),KeyNotFoundException=>new NotFoundResult(),InvalidOperationException=>new ObjectResult(new{error=e.Message}){StatusCode=502},_=>new ObjectResult(new{error="The operation could not be completed."}){StatusCode=500}};
}
public record CreateOffer(string? Name,OfferType Type,IReadOnlyList<OfferComponent>? Components,OfferRule? Rule);
public record UpdateOffer(string ETag,string Name,IReadOnlyList<OfferComponent>? Components,OfferRule? Rule);
public record OfferAction(string? ETag,string? Comment);
public record VerifyRequest(IReadOnlyList<OfferComponent>? Basket);
