import crypto from 'node:crypto';import { z } from 'zod';import type{ProductSnapshot,RaiSnapshot,Money,ProductOption,MarkupType}from'./models.js';
export const HOME='https://service.rai.nl/INTERSHOP/web/WFS/RAI-raievents-Site/en_US/devworld/EUR/ViewHomepage-Start';
export const TARGETS=['Food | Beverages | Catering','Stand construction items','Power, internet & Water'];
export function norm(s:string){return s.replace(/\s+/g,' ').trim()}
export function loose(s:string){return norm(s).toLowerCase().replace(/[^a-z0-9]+/g,'')}
export function hash(input:unknown,len=12){return crypto.createHash('sha256').update(typeof input==='string'?input:stable(input)).digest('hex').slice(0,len)}
export function stable(v:any):string{if(Array.isArray(v))return`[${v.map(stable).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')}}`;return JSON.stringify(v)}
export function ocId(parts:string[],max=100){const base=('rai-devworld-'+parts.filter(Boolean).join('-')).toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');return base.length<=max?base:base.slice(0,max-13).replace(/-$/,'')+'-'+hash(base,12)}
export function parseMoney(text:string,currency='EUR'):Money|null{const raw=norm(text);if(!raw)return null;const m=raw.match(/[-+]?\d[\d.,\s]*(?:[,.]\d{1,4})?/);if(!m)return null;let n=m[0].replace(/\s/g,'');const comma=n.lastIndexOf(','),dot=n.lastIndexOf('.');if(comma>-1&&dot>-1)n=comma>dot?n.replace(/\./g,'').replace(',','.'):n.replace(/,/g,'');else if(comma>-1)n=n.replace(',','.');const amount=Number(n);return Number.isFinite(amount)?{amount,currency:currency as 'EUR',rawText:raw}:null}
export function firstChildren<T>(children:T[]){return children.slice(0,3)}
export function firstProducts<T>(products:T[]){return products.slice(0,5)}
export function sourceHash(p:Omit<ProductSnapshot,'sourceHash'>){const copy:any={...p};delete copy.sourceHash;return hash(copy,32)}
export function dedupeProducts(products:ProductSnapshot[]){const map=new Map<string,ProductSnapshot>();for(const p of products){const key=p.sourceSku||p.sourceProductId||p.canonicalUrl;const existing=map.get(key);if(!existing){map.set(key,{...p,categoryPaths:[...p.categoryPaths]});continue}const seen=new Set(existing.categoryPaths.map(x=>x.join('\u0000')));for(const path of p.categoryPaths){const k=path.join('\u0000');if(!seen.has(k)){existing.categoryPaths.push(path);seen.add(k)}}}return [...map.values()]}
export function optionMarkup(base:number,value:{priceImpact?:Money;absolutePrice?:Money;markupType?:MarkupType}){if(value.absolutePrice)return {type:'AmountPerQuantity' as MarkupType,amount:Number((value.absolutePrice.amount-base).toFixed(2))};return {type:value.markupType||'NoMarkup' as MarkupType,amount:value.priceImpact?.amount||0}}
export function needsCompositeSpec(options:ProductOption[]){return options.some(o=>o.dependencies&&o.dependencies.length>0)}
export const snapshotSchema=z.object({schemaVersion:z.literal(1),complete:z.boolean(),source:z.object({system:z.string(),event:z.literal('DevWorld'),language:z.literal('en_US'),currency:z.literal('EUR'),homepageUrl:z.string().url(),scrapedAtUtc:z.string(),failure:z.string().optional(),skippedProducts:z.array(z.object({url:z.string(),sku:z.string().optional(),name:z.string().optional(),reason:z.string()})).optional(),skippedCategories:z.array(z.object({url:z.string(),categoryPath:z.array(z.string()),reason:z.string()})).optional()}),categories:z.array(z.any()),products:z.array(z.any())}).superRefine((s,ctx)=>{if(!s.complete)ctx.addIssue({code:'custom',message:`Snapshot is incomplete: ${s.source.failure||'unknown reason'}`});for(const p of s.products){const amount=p?.pricing?.basePrice?.amount;if(!Number.isFinite(amount))ctx.addIssue({code:'custom',message:`Missing price for ${p?.name}`});else if(amount<=0)ctx.addIssue({code:'custom',message:`Invalid non-positive price for ${p?.name}`});if(p?.pricing?.basePrice?.currency!=='EUR')ctx.addIssue({code:'custom',message:`Invalid currency for ${p?.name}`});if(loose(String(p?.name||''))==='shoppingcart')ctx.addIssue({code:'custom',message:`Invalid product name Shopping cart for ${p?.canonicalUrl||'unknown URL'}`});}});
export function validateSnapshot(s:unknown){return snapshotSchema.parse(s)}
