import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{chromium,Page}from'@playwright/test';import{HOME,TARGETS,firstChildren,firstProducts,loose,norm,ocId,parseMoney,sourceHash}from'./lib.js';import type{RaiSnapshot,ProductSnapshot}from'./models.js';
const __filename=fileURLToPath(import.meta.url);const __dirname=path.dirname(__filename);export const out=path.resolve(__dirname,'../data/rai-devworld.snapshot.json');
export type Link={text:string;href:string;cardText?:string;hasImage?:boolean;hasPrice?:boolean;title?:string};
const BLOCKED_URL_PARTS=['ViewProductCompare','ProductCompare','ViewCart','ViewBasket','AddProduct','AddToCart','ViewStandardCatalog-Browse','ViewHomepage','Login','Wishlist'];
export function isExcludedUrl(href:string){return BLOCKED_URL_PARTS.some(part=>href.toLowerCase().includes(part.toLowerCase()))}
export function isProductDetailUrl(href:string){if(isExcludedUrl(href))return false;return /(?:ViewProduct-(?:Show|Start)|Product-Show|ViewProductDetail|ProductID=|SKU=|sku=)/i.test(href)}
export function hasProductLikeCardContent(l:Link){const text=norm(`${l.title||''} ${l.cardText||''} ${l.text||''}`);const hasTitle=Boolean(norm(l.title||l.text));const hasPrice=Boolean(l.hasPrice||/(?:€|EUR)\s*[-+]?\d[\d.,\s]*/i.test(text));return hasTitle&&(hasPrice||Boolean(l.hasImage))}
export function isProductCardLink(l:Link){return isProductDetailUrl(l.href)&&hasProductLikeCardContent(l)}
async function links(page:Page){return page.locator('a').evaluateAll(as=>as.map((a:any)=>({text:(a.innerText||a.textContent||'').replace(/\s+/g,' ').trim(),href:a.href})).filter(x=>x.text&&x.href))}
export async function productLinks(page:Page){const candidates=await page.locator('article, li, [data-testid*="product" i], [class*="product" i], [id*="product" i]').evaluateAll((cards:any[])=>cards.flatMap(card=>{const cardText=(card.innerText||card.textContent||'').replace(/\s+/g,' ').trim();const hasImage=Boolean(card.querySelector('img'));const hasPrice=/(?:€|EUR)\s*[-+]?\d[\d.,\s]*/i.test(cardText);const title=(card.querySelector('h1,h2,h3,h4,[itemprop="name"]')?.textContent||'').replace(/\s+/g,' ').trim();return Array.from(card.querySelectorAll('a[href]')).map((a:any)=>({text:(a.innerText||a.textContent||'').replace(/\s+/g,' ').trim(),href:a.href,cardText,hasImage,hasPrice,title}))}));const seen=new Set<string>();return (candidates as Link[]).filter(isProductCardLink).filter(l=>!seen.has(l.href)&&seen.add(l.href)).slice(0,5)}
async function childCategoryLinks(page:Page){const all=await links(page);return all.filter(l=>/ViewStandardCatalog-Browse/i.test(l.href)&&!isExcludedUrl(l.href.replace('ViewStandardCatalog-Browse','')))}
export async function scrapeProduct(page:Page,href:string,card='',catPath:string[]):Promise<ProductSnapshot|null>{await page.goto(href,{waitUntil:'domcontentloaded',timeout:45000});await page.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{});const title=norm(await page.locator('h1').first().textContent().catch(()=>''))||card;const text=norm(await page.locator('body').innerText({timeout:5000}));const price=parseMoney(text.match(/(?:€|EUR)\s*[-+]?\d[\d.,\s]*/i)?.[0]||'');if(!title&&!price){console.warn(`Skipped non-product URL without product title or price: ${href}`);return null}if(!price){if(!isProductDetailUrl(href)||isExcludedUrl(href)){console.warn(`Skipped non-product URL without parseable price: ${href}`);return null}throw new Error(`Unable to parse required price for ${href}`)}const imgs=await page.locator('img').evaluateAll((els:any[])=>els.map(i=>i.currentSrc||i.src).filter(Boolean));const abs=[...new Set(imgs.map(u=>new URL(u,location.href).href).filter(u=>u.startsWith('https://')))];const sku=text.match(/(?:SKU|Item number|Product ID)\s*[:#]?\s*([A-Z0-9._-]+)/i)?.[1];const base:any={sourceSku:sku,name:title,cardDescription:card,fullDescription:text.slice(0,4000),canonicalUrl:page.url(),images:abs.map(u=>({thumbnailUrl:u,url:u})),pricing:{basePrice:price,rawPriceText:price.rawText,minQuantity:1,quantityMultiplier:1,priceBreaks:[{quantity:1,price}],options:[]},ordering:{notes:[]},attributes:[],sourceBreadcrumbs:catPath,categoryPaths:[catPath],ocId:ocId(['product',sku||title||href]),priceScheduleId:ocId(['ps',sku||title||href])};base.sourceHash=sourceHash(base);return base}
export async function run(){const headed=process.argv.includes('--headed');const browser=await chromium.launch({headless:!headed});const page=await browser.newPage();const scrapedAtUtc=new Date().toISOString();const snapshot:RaiSnapshot={schemaVersion:1,complete:false,source:{system:'RAI Amsterdam Exhibitor Services',event:'DevWorld',language:'en_US',currency:'EUR',homepageUrl:HOME,scrapedAtUtc},categories:[],products:[]};try{await page.goto(HOME,{waitUntil:'domcontentloaded',timeout:60000});await page.getByRole('button',{name:/accept|agree|allow/i}).click({timeout:5000}).catch(()=>{});const homeLinks=await links(page);for(const target of TARGETS){const l=homeLinks.find(x=>loose(x.text).includes(loose(target))||loose(target).includes(loose(x.text)));if(!l)continue;await traverse(l.href,[l.text],0,new Set<string>());}snapshot.complete=snapshot.products.length>0;snapshot.source.failure=snapshot.complete?undefined:'No target products were discovered';}catch(e){snapshot.source.failure=e instanceof Error?`${e.name}: ${e.message}`:String(e)}finally{await browser.close();fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(snapshot,null,2));if(!snapshot.complete){console.error(snapshot.source.failure);process.exitCode=1}else console.log(`Wrote ${snapshot.products.length} products to ${out}`)}
async function traverse(url:string,catPath:string[],depth:number,seen:Set<string>){if(depth>12||seen.has(url))return;seen.add(url);await page.goto(url,{waitUntil:'domcontentloaded',timeout:45000});await page.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{});const products=await productLinks(page);snapshot.categories.push({name:catPath.at(-1)||'',path:catPath,url:page.url(),listOrder:snapshot.categories.length,ocId:ocId(['cat',...catPath])});if(products.length){for(const pl of firstProducts(products)){try{const product=await scrapeProduct(page,pl.href,pl.text,catPath);if(product)snapshot.products.push(product);}catch(e){console.error(e)}}return;}for(const child of firstChildren(await childCategoryLinks(page))){await traverse(child.href,[...catPath,child.text],depth+1,seen)}}}
if(process.argv[1]&&path.resolve(process.argv[1])===__filename)run();
