import fs from'node:fs';import path from'node:path';import{chromium,Page}from'@playwright/test';import{HOME,TARGETS,firstChildren,firstProducts,loose,norm,ocId,parseMoney,sourceHash}from'./lib.js';import type{RaiSnapshot,ProductSnapshot}from'./models.js';
const out='tools/rai-devworld/data/rai-devworld.snapshot.json';
async function links(page:Page){return page.locator('a').evaluateAll(as=>as.map((a:any)=>({text:(a.innerText||a.textContent||'').replace(/\s+/g,' ').trim(),href:a.href})).filter(x=>x.text&&x.href))}
async function productLinks(page:Page){const all=await links(page);return all.filter(l=>/ViewProduct|Product-Show|SKU|ProductID/i.test(l.href)||l.href.includes('ViewProduct')).slice(0,5)}
async function childCategoryLinks(page:Page){const all=await links(page);return all.filter(l=>/ViewStandardCatalog-Browse/i.test(l.href))}
async function scrapeProduct(page:Page,href:string,card='',catPath:string[]):Promise<ProductSnapshot>{await page.goto(href,{waitUntil:'domcontentloaded',timeout:45000});await page.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{});const title=norm(await page.locator('h1').first().textContent().catch(()=>''))||card;const text=norm(await page.locator('body').innerText({timeout:5000}));const price=parseMoney(text.match(/(?:€|EUR)\s*[-+]?\d[\d.,\s]*/i)?.[0]||'');if(!price)throw new Error(`Unable to parse required price for ${href}`);const imgs=await page.locator('img').evaluateAll((els:any[])=>els.map(i=>i.currentSrc||i.src).filter(Boolean));const abs=[...new Set(imgs.map(u=>new URL(u,location.href).href).filter(u=>u.startsWith('https://')))];const sku=text.match(/(?:SKU|Item number|Product ID)\s*[:#]?\s*([A-Z0-9._-]+)/i)?.[1];const base:any={sourceSku:sku,name:title,cardDescription:card,fullDescription:text.slice(0,4000),canonicalUrl:page.url(),images:abs.map(u=>({thumbnailUrl:u,url:u})),pricing:{basePrice:price,rawPriceText:price.rawText,minQuantity:1,quantityMultiplier:1,priceBreaks:[{quantity:1,price}],options:[]},ordering:{notes:[]},attributes:[],sourceBreadcrumbs:catPath,categoryPaths:[catPath],ocId:ocId(['product',sku||title||href]),priceScheduleId:ocId(['ps',sku||title||href])};base.sourceHash=sourceHash(base);return base}
async function run(){const headed=process.argv.includes('--headed');const browser=await chromium.launch({headless:!headed});const page=await browser.newPage();const scrapedAtUtc=new Date().toISOString();const snapshot:RaiSnapshot={schemaVersion:1,complete:false,source:{system:'RAI Amsterdam Exhibitor Services',event:'DevWorld',language:'en_US',currency:'EUR',homepageUrl:HOME,scrapedAtUtc},categories:[],products:[]};try{await page.goto(HOME,{waitUntil:'domcontentloaded',timeout:60000});await page.getByRole('button',{name:/accept|agree|allow/i}).click({timeout:5000}).catch(()=>{});const homeLinks=await links(page);for(const target of TARGETS){const l=homeLinks.find(x=>loose(x.text).includes(loose(target))||loose(target).includes(loose(x.text)));if(!l)continue;await traverse(l.href,[l.text],0,new Set<string>());}snapshot.complete=snapshot.products.length>0;snapshot.source.failure=snapshot.complete?undefined:'No target products were discovered';}catch(e){snapshot.source.failure=e instanceof Error?`${e.name}: ${e.message}`:String(e)}finally{await browser.close();fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(snapshot,null,2));if(!snapshot.complete){console.error(snapshot.source.failure);process.exitCode=1}else console.log(`Wrote ${snapshot.products.length} products to ${out}`)}
async function traverse(url:string,catPath:string[],depth:number,seen:Set<string>){if(depth>12||seen.has(url))return;seen.add(url);await page.goto(url,{waitUntil:'domcontentloaded',timeout:45000});await page.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{});const products=await productLinks(page);snapshot.categories.push({name:catPath.at(-1)||'',path:catPath,url:page.url(),listOrder:snapshot.categories.length,ocId:ocId(['cat',...catPath])});if(products.length){for(const pl of firstProducts(products)){try{snapshot.products.push(await scrapeProduct(page,pl.href,pl.text,catPath));}catch(e){console.error(e)}}return;}for(const child of firstChildren(await childCategoryLinks(page))){await traverse(child.href,[...catPath,child.text],depth+1,seen)}}}
run();
