import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{chromium,Page}from'@playwright/test';import{HOME,TARGETS,firstChildren,firstProducts,loose,norm,ocId,parseMoney,sourceHash}from'./lib.js';import type{RaiSnapshot,ProductSnapshot}from'./models.js';
const __filename=fileURLToPath(import.meta.url);const __dirname=path.dirname(__filename);export const out=path.resolve(__dirname,'../data/rai-devworld.snapshot.json');export const debugDir=path.resolve(__dirname,'../debug');
export type Link={text:string;href:string;cardText?:string;hasImage?:boolean;hasPrice?:boolean;title?:string;source?:string};
export type RejectedLink=Link&{reasons:string[]};export type CategoryLinkDebug={currentUrl:string;currentCategoryName:string|null;allCandidateCategoryLinks:Link[];rejected:RejectedLink[];acceptedChildLinks:Link[];productLinkCandidates:Link[];first50VisibleAnchors:Link[]};
const BLOCKED_URL_PARTS=['ViewProductCompare','ProductCompare','ViewCart','ViewBasket','AddProduct','AddToCart','ViewStandardCatalog-Browse','ViewHomepage','Login','Wishlist'];
const BLOCKED_CHILD_URL_PARTS=['ViewProductCompare','ProductCompare','ViewCart','ViewBasket','AddProduct','AddToCart','Login','Wishlist','privacy','cookie','consent','Compare','Cart','Basket'];
export function isExcludedUrl(href:string){return BLOCKED_URL_PARTS.some(part=>href.toLowerCase().includes(part.toLowerCase()))}
export function isProductActionUrl(href:string){return BLOCKED_CHILD_URL_PARTS.some(part=>href.toLowerCase().includes(part.toLowerCase()))}
export function isProductDetailUrl(href:string){if(isExcludedUrl(href))return false;return /(?:ViewProduct-(?:Show|Start)|Product-Show|ViewProductDetail|ProductID=|SKU=|sku=)/i.test(href)}
export function hasProductLikeCardContent(l:Link){const text=norm(`${l.title||''} ${l.cardText||''} ${l.text||''}`);const hasTitle=Boolean(norm(l.title||l.text));const hasPrice=Boolean(l.hasPrice||/(?:€|EUR)\s*[-+]?\d[\d.,\s]*/i.test(text));return hasTitle&&(hasPrice||Boolean(l.hasImage))}
export function isProductCardLink(l:Link){return isProductDetailUrl(l.href)&&hasProductLikeCardContent(l)}
function sortedUrlWithoutHash(href:string){const u=new URL(href);u.hash='';const entries=[...u.searchParams.entries()].sort(([a,av],[b,bv])=>a.localeCompare(b)||av.localeCompare(bv));u.search='';for(const [k,v]of entries)u.searchParams.append(k,v);return u.href}
export function categoryNameOf(href:string){try{return new URL(href).searchParams.get('CategoryName')}catch{return null}}
export function rejectChildCategoryReasons(l:Link,currentUrl:string){const reasons:string[]=[];const text=norm(l.text);if(!text)reasons.push('empty link text');if(/^(consent)$/i.test(text)||loose(text)==='consent')reasons.push('consent link text');let u:URL|undefined,cur:URL|undefined;try{u=new URL(l.href);cur=new URL(currentUrl)}catch{reasons.push('invalid URL')}if(u&&cur){const rawSameExceptHash=sortedUrlWithoutHash(u.href)===sortedUrlWithoutHash(cur.href);if(rawSameExceptHash&&u.hash&&u.hash!==cur.hash)reasons.push('only # fragment change');if(rawSameExceptHash)reasons.push('same page URL without hash');if(isProductActionUrl(u.href))reasons.push('cookie/banner/privacy/action URL');const cat=u.searchParams.get('CategoryName'),currentCat=cur.searchParams.get('CategoryName');if(!cat)reasons.push('missing CategoryName');else if(currentCat&&cat===currentCat)reasons.push('same current CategoryName');if(!/ViewStandardCatalog-Browse/i.test(u.href))reasons.push('not a category browse URL')}return reasons}
export function filterChildCategoryLinks(candidates:Link[],currentUrl:string){const accepted:Link[]=[],rejected:RejectedLink[]=[],seen=new Set<string>();for(const l of candidates){const reasons=rejectChildCategoryReasons(l,currentUrl);let key='';try{key=sortedUrlWithoutHash(l.href)}catch{key=l.href}if(seen.has(key))reasons.push('duplicate normalized URL');if(reasons.length){rejected.push({...l,reasons});continue}seen.add(key);accepted.push({...l,href:key})}return{accepted,rejected}}
async function visibleAnchors(locator:any,source='all'):Promise<Link[]>{return locator.evaluateAll((as:any[],source:string)=>as.filter(a=>{const r=a.getBoundingClientRect();const s=getComputedStyle(a);return r.width>0&&r.height>0&&s.visibility!=='hidden'&&s.display!=='none'&&a.offsetParent!==null}).map(a=>({text:(a.innerText||a.textContent||'').replace(/\s+/g,' ').trim(),href:a.href,source})),source)}
async function links(page:Page){return visibleAnchors(page.locator('a[href]'))}
export async function productLinks(page:Page){const candidates=await page.locator('article, li, [data-testid*="product" i], [class*="product" i], [id*="product" i]').evaluateAll((cards:any[])=>cards.flatMap(card=>{const cardText=(card.innerText||card.textContent||'').replace(/\s+/g,' ').trim();const hasImage=Boolean(card.querySelector('img'));const hasPrice=/(?:€|EUR)\s*[-+]?\d[\d.,\s]*/i.test(cardText);const title=(card.querySelector('h1,h2,h3,h4,[itemprop="name"]')?.textContent||'').replace(/\s+/g,' ').trim();return Array.from(card.querySelectorAll('a[href]')).filter((a:any)=>{const r=a.getBoundingClientRect();const s=getComputedStyle(a);return r.width>0&&r.height>0&&s.visibility!=='hidden'&&s.display!=='none'}).map((a:any)=>({text:(a.innerText||a.textContent||'').replace(/\s+/g,' ').trim(),href:a.href,cardText,hasImage,hasPrice,title}))}));const seen=new Set<string>();return (candidates as Link[]).filter(isProductCardLink).filter(l=>!seen.has(l.href)&&seen.add(l.href)).slice(0,5)}
async function childCategoryLinks(page:Page,catPath:string[]){const currentUrl=page.url();const navSel='nav a[href], aside a[href], [role="navigation"] a[href], [class*="category" i] a[href], [class*="menu" i] a[href], [class*="tree" i] a[href], [class*="product-services" i] a[href]';const nav=await visibleAnchors(page.locator(navSel),'nav');const all=await links(page);let candidates=nav.filter(l=>/ViewStandardCatalog-Browse/i.test(l.href)||categoryNameOf(l.href));if(!candidates.length)candidates=all.filter(l=>/ViewStandardCatalog-Browse/i.test(l.href)||categoryNameOf(l.href));const productCandidates=await productLinks(page);const result=filterChildCategoryLinks(candidates,currentUrl);const debug:CategoryLinkDebug={currentUrl,currentCategoryName:categoryNameOf(currentUrl),allCandidateCategoryLinks:candidates,rejected:result.rejected,acceptedChildLinks:result.accepted,productLinkCandidates:productCandidates,first50VisibleAnchors:all.slice(0,50)};writeCategoryDebug(debug);for(const r of result.rejected.filter(r=>r.reasons.some(x=>/consent|fragment|same page|action|privacy|cookie/i.test(x))))console.log(`Skipped suspicious category link "${r.text||'(empty)'}" (${r.href}): ${r.reasons.join(', ')}`);console.log(`Category debug written: ${debugPathForCategory(debug.currentCategoryName||loose(catPath.at(-1)||'category'))}`);return result.accepted}
export function debugPathForCategory(categoryName:string){return path.join(debugDir,`category-links-${categoryName||'unknown'}.json`)}
export function writeCategoryDebug(debug:CategoryLinkDebug){fs.mkdirSync(debugDir,{recursive:true});fs.writeFileSync(debugPathForCategory(debug.currentCategoryName||'unknown'),JSON.stringify(debug,null,2))}
export async function scrapeProduct(page:Page,href:string,card='',catPath:string[]):Promise<ProductSnapshot|null>{await page.goto(href,{waitUntil:'domcontentloaded',timeout:45000});await page.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{});const title=norm(await page.locator('h1').first().textContent().catch(()=>''))||card;const text=norm(await page.locator('body').innerText({timeout:5000}));const price=parseMoney(text.match(/(?:€|EUR)\s*[-+]?\d[\d.,\s]*/i)?.[0]||'');if(!title&&!price){console.warn(`Skipped non-product URL without product title or price: ${href}`);return null}if(!price){if(!isProductDetailUrl(href)||isExcludedUrl(href)){console.warn(`Skipped non-product URL without parseable price: ${href}`);return null}throw new Error(`Unable to parse required price for ${href}`)}const imgs=await page.locator('img').evaluateAll((els:any[])=>els.map(i=>i.currentSrc||i.src).filter(Boolean));const abs=[...new Set(imgs.map(u=>new URL(u,location.href).href).filter(u=>u.startsWith('https://')))];const sku=text.match(/(?:SKU|Item number|Product ID)\s*[:#]?\s*([A-Z0-9._-]+)/i)?.[1];const base:any={sourceSku:sku,name:title,cardDescription:card,fullDescription:text.slice(0,4000),canonicalUrl:page.url(),images:abs.map(u=>({thumbnailUrl:u,url:u})),pricing:{basePrice:price,rawPriceText:price.rawText,minQuantity:1,quantityMultiplier:1,priceBreaks:[{quantity:1,price}],options:[]},ordering:{notes:[]},attributes:[],sourceBreadcrumbs:catPath,categoryPaths:[catPath],ocId:ocId(['product',sku||title||href]),priceScheduleId:ocId(['ps',sku||title||href])};base.sourceHash=sourceHash(base);return base}
export async function run(){const headed=process.argv.includes('--headed');const browser=await chromium.launch({headless:!headed});const page=await browser.newPage();const scrapedAtUtc=new Date().toISOString();const snapshot:RaiSnapshot={schemaVersion:1,complete:false,source:{system:'RAI Amsterdam Exhibitor Services',event:'DevWorld',language:'en_US',currency:'EUR',homepageUrl:HOME,scrapedAtUtc},categories:[],products:[]};try{await page.goto(HOME,{waitUntil:'domcontentloaded',timeout:60000});await page.getByRole('button',{name:/accept|agree|allow/i}).click({timeout:5000}).catch(()=>{});const homeLinks=await links(page);for(const target of TARGETS){const l=homeLinks.find(x=>loose(x.text).includes(loose(target))||loose(target).includes(loose(x.text)));if(!l)continue;await traverse(l.href,[l.text],0,new Set<string>());}snapshot.complete=snapshot.products.length>0;snapshot.source.failure=snapshot.complete?undefined:'No target products were discovered';}catch(e){snapshot.source.failure=e instanceof Error?`${e.name}: ${e.message}`:String(e)}finally{await browser.close();fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(snapshot,null,2));if(!snapshot.complete){console.error(snapshot.source.failure);process.exitCode=1}else console.log(`Wrote ${snapshot.products.length} products to ${out}`)}
async function traverse(url:string,catPath:string[],depth:number,seen:Set<string>){if(depth>12||seen.has(url))return;seen.add(url);console.log(`Visiting category path: ${catPath.join(' > ')}`);await page.goto(url,{waitUntil:'domcontentloaded',timeout:45000});await page.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{});console.log(`Current CategoryName: ${categoryNameOf(page.url())||'(none)'}`);const products=await productLinks(page);snapshot.categories.push({name:catPath.at(-1)||'',path:catPath,url:page.url(),listOrder:snapshot.categories.length,ocId:ocId(['cat',...catPath])});const children=await childCategoryLinks(page,catPath);console.log(`Accepted child count: ${children.length}`);console.log(`Accepted product count: ${products.length}`);if(products.length){for(const pl of firstProducts(products)){try{const product=await scrapeProduct(page,pl.href,pl.text,catPath);if(product)snapshot.products.push(product);}catch(e){console.error(e)}}return;}if(!children.length)throw new Error(`No accepted child categories or products for category path "${catPath.join(' > ')}" at ${page.url()}. See ${debugPathForCategory(categoryNameOf(page.url())||'unknown')}`);for(const child of firstChildren(children)){await traverse(child.href,[...catPath,child.text],depth+1,seen)}}}
if(process.argv[1]&&path.resolve(process.argv[1])===__filename)run();
