import {
  Badge,
  Box,
  Container,
  Divider,
  Grid,
  GridItem,
  HStack,
  Heading,
  Icon,
  SimpleGrid,
  Spinner,
  Text,
  VStack,
} from "@chakra-ui/react";
import {
  Address,
  LineItem,
  LineItems,
  Me,
  Order,
  Orders,
  RequiredDeep,
} from "ordercloud-javascript-sdk";
import { useCallback, useEffect, useMemo, useState } from "react";
import { TbCheckbox } from "react-icons/tb";
import { useLocation } from "react-router-dom";
import {
  getRaiDemoContextById,
  RAI_DEMO_CONTEXT_STORAGE_KEY,
  RaiDemoContext,
} from "../../demo/raiDemoContexts";
import OrderSummary from "./OrderSummary";

type RaiServiceDetailsType = "catering" | "utility" | "flooring";
type RaiServiceDetails = Record<string, string | number | boolean | undefined>;

const MOMENTUS_HANDOFF_STATUSES = [
  "OrderCloud order submitted",
  "Order calculation completed",
  "Queued for Momentus",
  "Supplier work orders prepared",
];

const getLineItemRai = (lineItem: LineItem) => (lineItem.xp as any)?.RAI;

const getMomentusOrderReference = (orderId?: string) => {
  const safeSuffix = (orderId || "DEMO00")
    .replace(/[^a-zA-Z0-9]/g, "")
    .slice(-6)
    .toUpperCase()
    .padStart(6, "0");

  return `MOM-DW26-${safeSuffix}`;
};

const getPaymentConfirmation = (order: RequiredDeep<Order>) => {
  const method = (order.xp as any)?.RAI?.Payment?.Method;
  const label =
    method === "card"
      ? "Pay now by card"
      : order.xp?.PaymentMethod || "Pay by invoice";
  const helperText =
    method === "card"
      ? "PSP authorization mocked for demo"
      : "Formal invoice generated by Momentus";

  return { label, helperText };
};

const getSupplierRoute = (type?: string) => {
  if (type === "catering") return "Catering operations";
  if (type === "utility") return "Electrical services";
  if (type === "flooring") return "Stand construction";
  return "Exhibitor services";
};

const formatServiceDetails = (
  type?: RaiServiceDetailsType,
  details?: RaiServiceDetails,
) => {
  if (!details) return "Service details captured for handoff.";

  if (type === "catering") {
    return `Delivery date: ${details.deliveryDate || "—"} · Time slot: ${details.deliveryTimeSlot || "—"} · Stand contact: ${details.standContactName || "—"}`;
  }

  if (type === "utility") {
    return `Grid location: ${details.standGridLocation || "—"} · Required by: ${details.requiredBy || "—"} · Technical contact phone: ${details.technicalContactPhone || "—"}`;
  }

  if (type === "flooring") {
    return `Area: ${details.standAreaM2 || "—"} m² · Ramp required: ${details.rampRequired || "—"} · Floor finish: ${details.floorFinish || "—"}`;
  }

  return "Service details captured for exhibitor services.";
};

const getConfirmationRaiContext = (
  lineItems: LineItem[],
): RaiDemoContext & { sourceLineItemContext?: Record<string, string> } => {
  const sourceLineItemContext = lineItems
    .map((lineItem) => getLineItemRai(lineItem)?.CapturedFor)
    .find(Boolean) as Record<string, string> | undefined;

  const selectedContext = getRaiDemoContextById(
    typeof window === "undefined"
      ? undefined
      : window.localStorage.getItem(RAI_DEMO_CONTEXT_STORAGE_KEY),
  );

  return {
    ...selectedContext,
    eventId: sourceLineItemContext?.EventID || selectedContext.eventId,
    exhibitorId:
      sourceLineItemContext?.ExhibitorID || selectedContext.exhibitorId,
    hall: sourceLineItemContext?.Hall || selectedContext.hall,
    standNumber:
      sourceLineItemContext?.StandNumber || selectedContext.standNumber,
    sourceLineItemContext,
  };
};

interface MomentusHandoffDemoProps {
  order: RequiredDeep<Order>;
  lineItems: LineItem[];
}

const MomentusHandoffDemo = ({
  order,
  lineItems,
}: MomentusHandoffDemoProps) => {
  const raiContext = useMemo(
    () => getConfirmationRaiContext(lineItems),
    [lineItems],
  );

  return (
    <Box
      border="1px solid"
      borderColor="blackAlpha.200"
      rounded="lg"
      p={5}
      w="full"
      bg="white"
    >
      {/* Demo-only: production would post the OrderCloud order and line-level xp/custom attributes to RAI middleware, then Momentus would create supplier work orders. */}
      <VStack alignItems="stretch" spacing={4}>
        <HStack justifyContent="space-between" alignItems="flex-start" gap={3}>
          <VStack alignItems="flex-start" gap={1}>
            <Heading size="md">Momentus handoff</Heading>
            <Text fontSize="sm" color="chakra-subtle-text">
              Integration: Mocked RAPI/services-layer handoff
            </Text>
          </VStack>
          <Badge colorScheme="purple" variant="subtle" whiteSpace="nowrap">
            Mocked Momentus integration
          </Badge>
        </HStack>

        <SimpleGrid columns={{ base: 1, md: 2 }} spacing={2}>
          {MOMENTUS_HANDOFF_STATUSES.map((status) => (
            <HStack key={status} spacing={2}>
              <Badge colorScheme="green" variant="solid">
                ✓
              </Badge>
              <Text fontSize="sm" fontWeight="600">
                {status}
              </Text>
            </HStack>
          ))}
        </SimpleGrid>

        <Divider />

        <SimpleGrid columns={{ base: 1, md: 2 }} spacing={2}>
          <Text fontSize="sm">
            <Text as="span" fontWeight="700">
              EventID:
            </Text>{" "}
            {raiContext.eventId}
          </Text>
          <Text fontSize="sm">
            <Text as="span" fontWeight="700">
              ExhibitorID:
            </Text>{" "}
            {raiContext.exhibitorId}
          </Text>
          <Text fontSize="sm">
            <Text as="span" fontWeight="700">
              AccountID:
            </Text>{" "}
            {raiContext.accountId}
          </Text>
          <Text fontSize="sm">
            <Text as="span" fontWeight="700">
              Hall:
            </Text>{" "}
            {raiContext.hall}
          </Text>
          <Text fontSize="sm">
            <Text as="span" fontWeight="700">
              StandNumber:
            </Text>{" "}
            {raiContext.standNumber}
          </Text>
          <Text fontSize="sm">
            <Text as="span" fontWeight="700">
              CompanyName:
            </Text>{" "}
            {raiContext.companyName}
          </Text>
        </SimpleGrid>

        <Box bg="blackAlpha.50" rounded="md" p={3}>
          <Text fontSize="sm" fontWeight="700">
            Momentus Order: {getMomentusOrderReference(order.ID)}
          </Text>
          <Text fontSize="xs" color="chakra-subtle-text">
            Integration: Mocked RAPI/services-layer handoff
          </Text>
        </Box>

        <VStack alignItems="stretch" spacing={3}>
          {lineItems.map((lineItem) => {
            const rai = getLineItemRai(lineItem);
            const type = rai?.ServiceDetailsType as
              | RaiServiceDetailsType
              | undefined;
            return (
              <Box
                key={lineItem.ID || lineItem.ProductID}
                borderTop="1px solid"
                borderColor="blackAlpha.100"
                pt={3}
              >
                <HStack
                  justifyContent="space-between"
                  alignItems="flex-start"
                  gap={3}
                >
                  <VStack alignItems="flex-start" gap={1}>
                    <Text fontSize="sm" fontWeight="700">
                      {lineItem.Product?.Name || lineItem.ProductID}
                    </Text>
                    <Text fontSize="xs" color="chakra-subtle-text">
                      Supplier route: {getSupplierRoute(type)}
                    </Text>
                    <Text fontSize="xs" color="chakra-subtle-text">
                      {formatServiceDetails(type, rai?.ServiceDetails)}
                    </Text>
                  </VStack>
                  <Badge colorScheme="blue" variant="subtle">
                    Qty {lineItem.Quantity}
                  </Badge>
                </HStack>
              </Box>
            );
          })}
        </VStack>
      </VStack>
    </Box>
  );
};

const OrderConfirmation = (): JSX.Element => {
  const [loading, setLoading] = useState(true);
  const [lineItems, setLineItems] = useState<LineItem[]>([]);
  const [order, setOrder] = useState<RequiredDeep<Order>>();
  const [shippingAddress, setShippingAddress] = useState<Address>();
  const location = useLocation();

  const getOrder = useCallback(async () => {
    const searchParams = new URLSearchParams(location.search);
    const orderId = searchParams.get("orderID");

    if (!orderId) {
      console.error("Order ID not found in URL");
      setLoading(false);
      return;
    }

    const result = await Orders.Get("Outgoing", orderId);
    setOrder(result);
    setLoading(false);
  }, [location.search]);

  const getLineItems = useCallback(async () => {
    if (!order?.ID) return;
    const result = await LineItems.List("Outgoing", order.ID);
    setLineItems(result.Items);
  }, [order]);

  const getShippingAddress = useCallback(async () => {
    if (!order?.ShippingAddressID) return;
    const addressResult = await Me.GetAddress(order.ShippingAddressID);
    setShippingAddress(addressResult);
  }, [order]);

  useEffect(() => {
    getOrder();
  }, [getOrder]);

  useEffect(() => {
    getLineItems();
    getShippingAddress();
  }, [order, getLineItems, getShippingAddress]);

  if (loading) {
    return (
      <Container maxW="container.lg" centerContent>
        <Spinner size="xl" />
      </Container>
    );
  }

  if (!order) {
    return (
      <Container maxW="container.lg" centerContent>
        <Heading>Order not found</Heading>
        <Text>
          We couldn't find the order information. Please check the URL and try
          again.
        </Text>
      </Container>
    );
  }

  const paymentConfirmation = getPaymentConfirmation(order);

  return (
    <Grid
      gridTemplateColumns={{ md: "3fr 2fr" }}
      w="full"
      h="100vh"
      justifyItems="stretch"
      flex="1"
    >
      <GridItem alignSelf="flex-end" h="full">
        <Container maxW="container.lg" mx="0" ml="auto" p={{ base: 6, lg: 12 }}>
          <VStack alignItems="flex-start" flex="1" minH="500px">
            <HStack gap="3" alignItems="center">
              <Icon
                layerStyle="icon.subtle"
                boxSize="icon.2xl"
                color="primary"
                as={TbCheckbox}
              />
              <VStack alignItems="flex-start" gap="0">
                <Heading size="xl">Order confirmed</Heading>
                <Text color="chakra-subtle-text">Order ID: {order.ID}</Text>
              </VStack>
            </HStack>
            <Divider my="3" />
            <VStack justifyContent="flex-start" alignItems="flex-start">
              <HStack alignItems="flex-start">
                <VStack alignItems="flex-start" gap="0">
                  <Text fontWeight="bold">
                    {order.FromUser?.FirstName} {order.FromUser?.LastName}
                  </Text>
                  {shippingAddress && (
                    <>
                      <Text>
                        {shippingAddress.Street1} {shippingAddress.Street2}
                      </Text>
                      <Text>
                        {shippingAddress.City}, {shippingAddress.State}{" "}
                        {shippingAddress.Zip}
                      </Text>
                    </>
                  )}
                  <Text mt="3">
                    {order.FromUser?.Phone}
                    {order.FromUser?.Phone && "|"} {order.FromUser?.Email}
                  </Text>
                </VStack>
              </HStack>
            </VStack>
            <Divider my="3" />
            <VStack alignItems="flex-start" gap="0">
              <Text fontWeight="700">
                Payment method: {paymentConfirmation.label}
              </Text>
              <Text fontSize="sm" color="chakra-subtle-text">
                {paymentConfirmation.helperText}
              </Text>
            </VStack>
            <MomentusHandoffDemo order={order} lineItems={lineItems} />
          </VStack>
        </Container>
      </GridItem>
      <GridItem bgColor="blackAlpha.100" h="full">
        <Container maxW="container.sm" mx="0" mr="auto" p={{ base: 6, lg: 12 }}>
          <OrderSummary order={order} lineItems={lineItems} />
        </Container>
      </GridItem>
    </Grid>
  );
};

export default OrderConfirmation;
