import {
  Badge,
  Box,
  Button,
  Card,
  CardBody,
  Heading,
  Radio,
  RadioGroup,
  Text,
  VStack,
} from "@chakra-ui/react";
import { useMemo } from "react";
import { PAYMENT_PROVIDER, PAYMENT_PROVIDERS } from "../../../constants";
import { BlueSnap } from "../Payment/BlueSnap";
import { CardConnect } from "../Payment/CardConnect";
import { PayPal } from "../Payment/PayPal";
import { Stripe } from "../Payment/Stripe";

export type RaiPaymentMethod = "invoice" | "card";

export const RAI_PAYMENT_METHOD_LABELS: Record<RaiPaymentMethod, string> = {
  invoice: "Pay by invoice",
  card: "Pay now by card",
};

type CartPaymentPanelProps = {
  paymentMethod: RaiPaymentMethod;
  setPaymentMethod: (paymentMethod: RaiPaymentMethod) => void;
  submitOrder: () => void;
  submitting: boolean;
};

const PaymentMapper = (provider: PAYMENT_PROVIDERS) => {
  switch (provider) {
    case PAYMENT_PROVIDERS.STRIPE:
      return <Stripe />;
    case PAYMENT_PROVIDERS.CARD_CONNECT:
      return <CardConnect />;
    case PAYMENT_PROVIDERS.BLUESNAP:
      return <BlueSnap />;
    case PAYMENT_PROVIDERS.PAYPAL:
      return <PayPal />;
    default:
      null;
  }
};

const paymentMethodDescriptions: Record<RaiPaymentMethod, string> = {
  invoice:
    "Enabled by Momentus account flag. Formal invoice generated by Momentus after order confirmation.",
  card: "Optional PSP flow for exhibitors who prefer immediate payment.",
};

export const CartPaymentPanel = ({
  paymentMethod,
  setPaymentMethod,
  submitOrder,
  submitting,
}: CartPaymentPanelProps) => {
  const PaymentElement = useMemo(() => {
    return PaymentMapper(PAYMENT_PROVIDER);
  }, []);

  return (
    <>
      <Card variant="flat" shadow="none" bgColor="whiteAlpha.800" w="full">
        <CardBody>
          <VStack alignItems="stretch" spacing={4}>
            <Box>
              <Heading size="md" mb={2}>
                Payment method
              </Heading>
              <Badge colorScheme="purple" variant="subtle">
                Mocked Momentus payment terms
              </Badge>
            </Box>

            <RadioGroup
              value={paymentMethod}
              onChange={(value) => setPaymentMethod(value as RaiPaymentMethod)}
              as={VStack}
              alignItems="stretch"
              spacing={3}
              sx={{
                ".chakra-radio__label": {
                  width: "full",
                },
              }}
            >
              {(Object.keys(RAI_PAYMENT_METHOD_LABELS) as RaiPaymentMethod[]).map(
                (method) => {
                  const isSelected = paymentMethod === method;
                  return (
                    <Radio
                      key={method}
                      value={method}
                      w="full"
                      alignItems="flex-start"
                    >
                      <Box
                        border="1px solid"
                        borderColor={isSelected ? "primary" : "blackAlpha.200"}
                        bg={isSelected ? "blackAlpha.50" : "white"}
                        rounded="lg"
                        p={4}
                        w="full"
                      >
                        <Text fontWeight="700">
                          {RAI_PAYMENT_METHOD_LABELS[method]}
                        </Text>
                        <Text fontSize="sm" color="chakra-subtle-text" mt={1}>
                          {paymentMethodDescriptions[method]}
                        </Text>
                      </Box>
                    </Radio>
                  );
                },
              )}
            </RadioGroup>
          </VStack>
        </CardBody>
      </Card>

      {paymentMethod === "card" && PaymentElement}

      <Button
        alignSelf="flex-end"
        onClick={submitOrder}
        mt={6}
        isDisabled={submitting}
      >
        {submitting ? "Submitting" : "Submit Order"}
      </Button>
    </>
  );
};
