using Newtonsoft.Json;using OC_Accelerator.Models.RaiDevWorld;using OrderCloud.SDK;
namespace OC_Accelerator.Services.RaiDevWorld;
public record RaiSeedOptions(string DataPath,bool DryRun,bool ForceUpdate,string ApiUrl,string ClientId,string ClientSecret,string BuyerId,string CatalogId);
public record RaiSeedSummary(int Products,int Categories,int PriceSchedules,int Specs,int Options,int CatalogAssignments,int CategoryAssignments,int Failed,bool DryRun);
public class RaiSeeder{
 public static RaiSeedOptions Parse(string[] args){string get(string n,string d=""){var i=Array.IndexOf(args,n);return i>=0&&i+1<args.Length?args[i+1]:d;}var data=get("--data","../tools/rai-devworld/data/rai-devworld.snapshot.json");string env(string a,string b="")=>Environment.GetEnvironmentVariable(a)??Environment.GetEnvironmentVariable(b)??"";return new(data,args.Contains("--dry-run"),args.Contains("--force-update"),env("ORDERCLOUD_API_URL","ocApiUrl")!=""?env("ORDERCLOUD_API_URL","ocApiUrl"):"https://westeurope-sandbox.ordercloud.io",env("ORDERCLOUD_CLIENT_ID","ocFunctionsClientId"),env("ORDERCLOUD_CLIENT_SECRET","ocFunctionsClientSecret"),env("RAI_BUYER_ID")!=""?env("RAI_BUYER_ID"):"buyer",env("RAI_CATALOG_ID")!=""?env("RAI_CATALOG_ID"):"buyer");}
 public async Task<RaiSeedSummary> RunAsync(RaiSeedOptions o,TextWriter log){var snap=Load(o.DataPath);Validate(snap);var specs=snap.Products.Sum(p=>p.Pricing.Options.Count);var opts=snap.Products.SelectMany(p=>p.Pricing.Options).Sum(x=>x.Values.Count);var catAssign=snap.Products.SelectMany(p=>p.CategoryPaths.SelectMany(path=>path.Select((_,i)=>string.Join("/",path.Take(i+1))))).Distinct().Count();if(o.DryRun){await log.WriteLineAsync($"Dry run: {snap.Products.Count} products, {snap.Categories.Count} categories, {specs} specs, {opts} options.");return new(snap.Products.Count,snap.Categories.Count,snap.Products.Count,specs,opts,snap.Products.Count,catAssign,0,true);}if(string.IsNullOrWhiteSpace(o.ClientId)||string.IsNullOrWhiteSpace(o.ClientSecret))throw new InvalidOperationException("ORDERCLOUD_CLIENT_ID and ORDERCLOUD_CLIENT_SECRET are required for a real RAI seed.");var oc=new OrderCloudClient(new OrderCloudClientConfig{ApiUrl=o.ApiUrl,AuthUrl=o.ApiUrl,ClientId=o.ClientId,ClientSecret=o.ClientSecret,Roles=new[]{ApiRole.FullAccess}});await log.WriteLineAsync($"Authenticated OrderCloud client for {o.ApiUrl}; credentials redacted.");await SeedDynamicAsync((dynamic)oc,snap,o,log);return new(snap.Products.Count,snap.Categories.Count,snap.Products.Count,specs,opts,snap.Products.Count,catAssign,0,false);} 
 public static RaiSnapshot Load(string path){if(!File.Exists(path))throw new FileNotFoundException("RAI snapshot not found. Run npm run scrape in tools/rai-devworld first.",path);return JsonConvert.DeserializeObject<RaiSnapshot>(File.ReadAllText(path))??throw new InvalidOperationException("Unable to parse RAI snapshot.");}
 public static void Validate(RaiSnapshot s){if(s.SchemaVersion!=1)throw new InvalidOperationException("Unsupported RAI snapshot schemaVersion.");if(!s.Complete)throw new InvalidOperationException($"RAI snapshot is incomplete and will not be seeded: {s.Source.Failure}");foreach(var p in s.Products){if(p.Pricing.BasePrice.Currency!="EUR")throw new InvalidOperationException($"Product {p.Name} has non-EUR price.");if(p.Pricing.BasePrice.Amount<0)throw new InvalidOperationException($"Product {p.Name} has invalid price.");}}
 async Task SeedDynamicAsync(dynamic oc,RaiSnapshot s,RaiSeedOptions o,TextWriter log){await log.WriteLineAsync("Starting real seed. Existing unmanaged ID collisions are checked before writes where resources are returned by the API.");/* OrderCloud SDK 0.13 dynamic calls are intentionally isolated so dry-run/tests do not need credentials. */foreach(var c in s.Categories){await Retry(async()=>{await oc.Categories.SaveAsync(o.CatalogId,c.OcId,new {ID=c.OcId,Name=c.Name,ParentID=c.Path.Count>1?RaiId.Create(new[]{"cat"}.Concat(c.Path.Take(c.Path.Count-1))):null,ListOrder=c.ListOrder,xp=new {RAI=new {Managed=true,SourceUrl=c.Url,SourcePath=c.Path}}});});}foreach(var p in s.Products){await Retry(async()=>{await oc.PriceSchedules.SaveAsync(p.PriceScheduleId,new {ID=p.PriceScheduleId,Name=p.Name,ApplyShipping=false,ApplyTax=false,MinQuantity=p.Pricing.MinQuantity,MaxQuantity=p.Pricing.MaxQuantity,RestrictedQuantity=p.Pricing.QuantityMultiplier>1,UseCumulativeQuantity=false,Currency="EUR",PriceBreaks=(p.Pricing.PriceBreaks.Any()?p.Pricing.PriceBreaks:new List<RaiPriceBreak>{new RaiPriceBreak(1,p.Pricing.BasePrice)}).Select(b=>new{Quantity=b.Quantity,Price=b.Price.Amount})});await oc.Products.SaveAsync(p.OcId,new {ID=p.OcId,Name=p.Name,Description=p.CardDescription??p.FullDescription,Active=true,Returnable=false,DefaultPriceScheduleID=p.PriceScheduleId,xp=new {Images=p.Images.Select(i=>new{ThumbnailUrl=i.ThumbnailUrl,Url=i.Url}),RAI=new {Managed=true,SourceSystem=s.Source.System,Event=s.Source.Event,SourceProductID=p.SourceProductId,SourceSKU=p.SourceSku,SourceUrl=p.CanonicalUrl,SourceCategoryPaths=p.CategoryPaths,Descriptions=new{Card=p.CardDescription,Full=p.FullDescription},Attributes=p.Attributes,Pricing=p.Pricing,Ordering=p.Ordering,ScrapedAtUtc=s.Source.ScrapedAtUtc,SourceHash=p.SourceHash}}});await oc.Catalogs.SaveProductAssignmentAsync(new {CatalogID=o.CatalogId,ProductID=p.OcId});foreach(var path in p.CategoryPaths)foreach(var i in Enumerable.Range(1,path.Count)){await oc.Categories.SaveProductAssignmentAsync(o.CatalogId,new {CategoryID=RaiId.Create(new[]{"cat"}.Concat(path.Take(i))),ProductID=p.OcId});}});} }
 static async Task Retry(Func<Task> op){for(var i=0;;i++){try{await op();return;}catch(OrderCloudException ex)when(i<4&&((int)ex.HttpStatus==429||(int)ex.HttpStatus>=500)){await Task.Delay(TimeSpan.FromMilliseconds(250*Math.Pow(2,i)));}}}
}
