import { Tokens } from 'ordercloud-javascript-sdk'
export type OfferType='Bundle'|'BuyThreePayTwo'|'SegmentDiscount'
export interface Component{productId:string;title?:string;quantity:number;unitPrice:number;includedFree:boolean;required:boolean}
export interface Rule{selectorType:string;selectorId:string;minimumQuantity:number;discountPercent:number;productIds?:string[]}
export interface Offer{id:string;name:string;type:OfferType;status:string;owner:string;revision:number;updatedAt:string;components:Component[];rule?:Rule;history:{at:string;actor:string;action:string;comment?:string}[];publicationError?:string;publishedResources?:Record<string,string>}
export interface Document{offer:Offer;eTag:string}
export interface CatalogItem{id:string;name:string;entityType:string;unitPrice?:number;imageUrl?:string;authorIds:string[];genreIds:string[];availability?:string}
export interface CatalogPage{items:CatalogItem[];authors:{id:string;name:string;productCount:number}[];genres:{id:string;name:string;productCount:number}[];page:number;pageSize:number;totalCount:number;totalPages:number}
export interface Verification{orderId:string;lines:{productId:string;title:string;quantity:number;unitPrice:number;lineTotal:number;qualifies:boolean;discount:number}[];subtotal:number;discount:number;total:number;appliedPromotions:string[];discrepancies:string[];resourceIds:Record<string,string>}
const base=(import.meta.env.VITE_PELCKMANS_API_BASE_URL||'').replace(/\/$/,'')
async function call<T>(path:string,init?:RequestInit):Promise<T>{const token=Tokens.GetAccessToken();if(!token)throw new Error('Sign in to use Bundles & Offers.');let response:Response;try{response=await fetch(`${base}/api/pelckmans${path}`,{...init,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...init?.headers}})}catch{throw new Error('Bundles & Offers API is unreachable. Check VITE_PELCKMANS_API_BASE_URL and local Functions.')}const text=await response.text();let body:unknown={};try{body=text?JSON.parse(text):{}}catch{throw new Error(`The API returned an unexpected non-JSON response (${response.status}).`)}if(!response.ok)throw new Error((body as {error?:string}).error||`Request failed (${response.status})`);return body as T}
export const api={capabilities:()=>call<{username:string;editor:boolean;approver:boolean}>('/capabilities'),list:()=>call<Document[]>('/offers'),get:(id:string)=>call<Document>(`/offers/${id}`),catalog:(search='',page=1)=>call<CatalogPage>(`/catalog?search=${encodeURIComponent(search)}&page=${page}&pageSize=25`),create:(body:Partial<Offer>)=>call<Document>('/offers',{method:'POST',body:JSON.stringify(body)}),update:(id:string,body:{eTag:string;name:string;components:Component[];rule?:Rule})=>call<Document>(`/offers/${id}`,{method:'PUT',body:JSON.stringify(body)}),duplicate:(id:string)=>call<Document>(`/offers/${id}/duplicate`,{method:'POST',body:'{}'}),preview:(id:string,basket?:Component[])=>call<{lines:{title:string;quantity:number;unitPrice:number;discount:number}[];subtotal:number;discount:number;payable:number;label:string}>(`/offers/${id}/preview`,{method:'POST',body:JSON.stringify({basket})}),action:(id:string,action:string,eTag:string,comment?:string)=>call<Document>(`/offers/${id}/${action}`,{method:'POST',body:JSON.stringify({eTag,comment})}),verify:(id:string,basket?:Component[])=>call<Verification>(`/offers/${id}/verify`,{method:'POST',body:JSON.stringify({basket})})}
