import { Alert,AlertIcon,Badge,Box,Button,Card,CardBody,Container,Divider,FormControl,FormLabel,Heading,HStack,Input,NumberInput,NumberInputField,Radio,RadioGroup,Select,SimpleGrid,Spinner,Stack,Table,Tbody,Td,Text,Th,Thead,Tr,useToast } from '@chakra-ui/react'
import { useEffect,useState } from 'react'
import { Link,useNavigate,useParams } from 'react-router-dom'
import { api,Document,OfferType } from './api'

const templates:{type:OfferType;title:string;description:string}[]=[
  {type:'Bundle',title:'Book & event bundle',description:'Package books with events or signing experiences.'},
  {type:'BuyThreePayTwo',title:'Buy 3, pay 2',description:'Give one cheapest qualifying book free.'},
  {type:'SegmentDiscount',title:'Author or genre discount',description:'Reward a minimum quantity from one author or genre.'}]
const eur=(n:number)=>new Intl.NumberFormat('nl-BE',{style:'currency',currency:'EUR'}).format(n)
export default function PelckmansWorkspace({mode}:{mode?:'new'|'detail'|'review'}){
 const [docs,setDocs]=useState<Document[]>([]),[caps,setCaps]=useState<{username:string;editor:boolean;approver:boolean}>(),[error,setError]=useState(''),[busy,setBusy]=useState(true); const {offerId}=useParams();
 useEffect(()=>{Promise.all([api.capabilities(),api.list()]).then(([c,d])=>{setCaps(c);setDocs(d)}).catch(e=>setError(e.message)).finally(()=>setBusy(false))},[])
 if(busy)return <Container py="10"><Spinner/></Container>; if(error)return <Container py="10"><Alert status="error"><AlertIcon/>{error}</Alert></Container>
 if(mode==='new')return <Wizard/>; if(offerId){const d=docs.find(x=>x.offer.id===offerId); return d?<OfferDetail initial={d} approver={!!caps?.approver}/>:<Container py="10"><Alert status="warning"><AlertIcon/>Offer not found or not available.</Alert></Container>}
 const review=docs.filter(x=>x.offer.status==='PendingApproval')
 return <Container maxW="7xl" py="8"><HStack justify="space-between"><Box><Heading>Bundles &amp; Offers</Heading><Text color="gray.600">Create customer-ready Pelckmans packages and promotions through a governed approval workflow.</Text></Box>{caps?.editor&&<Button as={Link} to="/pelckmans/new" colorScheme="blue">Create bundle or offer</Button>}</HStack>
 <Heading size="md" mt="10" mb="4">Start with a template</Heading><SimpleGrid columns={{base:1,md:3}} spacing="5">{templates.map(t=><Card key={t.type}><CardBody><Heading size="sm">{t.title}</Heading><Text my="3">{t.description}</Text>{caps?.editor&&<Button as={Link} to={`/pelckmans/new?type=${t.type}`} size="sm">Use template</Button>}</CardBody></Card>)}</SimpleGrid>
 <Heading size="md" mt="10" mb="4">Saved offers</Heading><OfferTable docs={docs}/>{caps?.approver&&<><Heading size="md" mt="10" mb="4">Review queue <Badge>{review.length}</Badge></Heading><OfferTable docs={review} review/></>}</Container>
}
function OfferTable({docs,review}:{docs:Document[];review?:boolean}){return docs.length?<Table variant="simple"><Thead><Tr><Th>Offer</Th><Th>Type</Th><Th>Status</Th><Th>Owner</Th><Th>Last update</Th><Th/></Tr></Thead><Tbody>{docs.map(d=><Tr key={d.offer.id}><Td fontWeight="semibold">{d.offer.name}</Td><Td>{templates.find(t=>t.type===d.offer.type)?.title}</Td><Td><Badge>{d.offer.status}</Badge></Td><Td>{d.offer.owner}</Td><Td>{new Date(d.offer.updatedAt).toLocaleString()}</Td><Td><Button as={Link} to={`/pelckmans/offers/${d.offer.id}${review?'/review':''}`} size="xs">{review?'Review':'Open'}</Button></Td></Tr>)}</Tbody></Table>:<Text color="gray.500">No offers here yet.</Text>}
function Wizard(){const query=new URLSearchParams(location.search);const [step,setStep]=useState(1),[type,setType]=useState<OfferType>((query.get('type') as OfferType)||'Bundle'),[name,setName]=useState(''),[selector,setSelector]=useState(''),[minimum,setMinimum]=useState(4),[percent,setPercent]=useState(10),[saving,setSaving]=useState(false);const nav=useNavigate(),toast=useToast();
 const save=async()=>{setSaving(true);try{const d=await api.create({name,type,components:[],rule:type==='Bundle'?undefined:{selectorType:'category',selectorId:selector,minimumQuantity:type==='BuyThreePayTwo'?3:minimum,discountPercent:type==='BuyThreePayTwo'?0:percent,productIds:[]}});toast({status:'success',title:'Draft saved'});nav(`/pelckmans/offers/${d.offer.id}`)}catch(e){toast({status:'error',title:(e as Error).message})}finally{setSaving(false)}}
 return <Container maxW="5xl" py="8"><Heading size="lg">Create bundle or offer</Heading><Text color="gray.600">Step {step} of 4 · {['Choose a template','Select products or audience','Configure pricing and conditions','Preview and submit'][step-1]}</Text><Divider my="6"/>
 {step===1&&<RadioGroup value={type} onChange={x=>setType(x as OfferType)}><Stack>{templates.map(t=><Card key={t.type} variant="outline"><CardBody><Radio value={t.type}><b>{t.title}</b><Text>{t.description}</Text></Radio></CardBody></Card>)}</Stack></RadioGroup>}
 {step===2&&<Stack><Alert status="info"><AlertIcon/>Product discovery is loaded from OrderCloud after the draft is saved; raw IDs are never requested for products.</Alert>{type!=='Bundle'&&<FormControl isRequired><FormLabel>Author or genre</FormLabel><Select placeholder="Choose from discovered categories" value={selector} onChange={e=>setSelector(e.target.value)}><option value="PEL_CATEGORY_DEMO">Pelckmans discovered selection</option></Select></FormControl>}</Stack>}
 {step===3&&<Stack><FormControl isRequired><FormLabel>Offer name</FormLabel><Input value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></FormControl>{type==='SegmentDiscount'&&<><FormControl><FormLabel>Minimum qualifying quantity</FormLabel><NumberInput value={minimum} min={2} max={20} onChange={(_,n)=>setMinimum(n)}><NumberInputField/></NumberInput></FormControl><FormControl><FormLabel>Discount percentage</FormLabel><NumberInput value={percent} min={1} max={50} onChange={(_,n)=>setPercent(n)}><NumberInputField/></NumberInput></FormControl></>}</Stack>}
 {step===4&&<Card><CardBody><Badge colorScheme="orange">Estimated preview</Badge><Heading size="md" mt="2">{name||'Untitled offer'}</Heading><Text>{templates.find(t=>t.type===type)?.description}</Text><Text mt="4" color="gray.600">Save the draft to resolve current Individual Customer prices. Saving does not publish or approve anything.</Text></CardBody></Card>}
 <HStack mt="8" justify="space-between"><Button onClick={()=>step===1?nav('/pelckmans'):setStep(step-1)}>{step===1?'Cancel':'Back'}</Button>{step<4?<Button colorScheme="blue" onClick={()=>setStep(step+1)}>Next</Button>:<Button colorScheme="blue" isLoading={saving} isDisabled={!name.trim()} onClick={save}>Save draft</Button>}</HStack></Container>}
function OfferDetail({initial,approver}:{initial:Document;approver:boolean}){const [doc,setDoc]=useState(initial),[preview,setPreview]=useState<Awaited<ReturnType<typeof api.preview>>>(),[comment,setComment]=useState(''),[error,setError]=useState('');const act=async(a:string)=>{try{setDoc(await api.action(doc.offer.id,a,doc.eTag,comment));setError('')}catch(e){setError((e as Error).message)}};const o=doc.offer;
 return <Container maxW="5xl" py="8"><HStack justify="space-between"><Box><Badge>{o.status}</Badge><Heading>{o.name}</Heading><Text>Owned by {o.owner} · revision {o.revision}</Text></Box><Button as={Link} to="/pelckmans">Back to workspace</Button></HStack>{error&&<Alert status="error" mt="4"><AlertIcon/>{error}</Alert>}<Card mt="6"><CardBody><Heading size="md">Plain-language summary</Heading><Text mt="2">{templates.find(t=>t.type===o.type)?.description}</Text>{o.publicationError&&<Alert status="error" mt="4"><AlertIcon/>Publication did not complete: {o.publicationError}</Alert>}</CardBody></Card>
 <HStack mt="5">{o.status==='Draft'&&<><Button onClick={async()=>setPreview(await api.preview(o.id))}>Estimated preview</Button><Button colorScheme="blue" onClick={()=>act('submit')}>Submit for approval</Button></>}{approver&&o.status==='PendingApproval'&&<><Button colorScheme="green" onClick={()=>act('approve')}>Approve exact revision</Button><Input placeholder="Required rejection comment" value={comment} onChange={e=>setComment(e.target.value)}/><Button colorScheme="red" isDisabled={!comment.trim()} onClick={()=>act('reject')}>Reject</Button></>}{approver&&o.status==='Approved'&&<Button colorScheme="blue" onClick={()=>act('publish')}>Publish to OrderCloud</Button>}{o.status==='Published'&&<Alert status="info"><AlertIcon/>Native verification is available only after the verification endpoint is configured.</Alert>}</HStack>
 {preview&&<Card mt="5"><CardBody><Badge colorScheme="orange">{preview.label}</Badge>{preview.lines.map((l,i)=><Text key={i}>{l.quantity} × {l.title}: {eur(l.unitPrice)} {l.discount>0&&`− ${eur(l.discount)}`}</Text>)}<Heading size="sm" mt="3">Payable: {eur(preview.payable)}</Heading></CardBody></Card>}<Heading size="sm" mt="8">Audit history</Heading>{o.history.map((h,i)=><Text key={i}>{new Date(h.at).toLocaleString()} · {h.actor} · {h.action}{h.comment&&`: ${h.comment}`}</Text>)}</Container>}
